services:
  front:
    platform: linux/amd64
    container_name: todo_front
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    platform: linux/amd64
    container_name: todo_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
      - 5555:5555
    command: ['npm', 'run', 'dev']
    env_file:
      - env.backend
    depends_on:
      - db
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: todo_db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - env.mysql
volumes:
  db_data:
